### ISSUE TITLE
Mangas Not Found

### ISSUE THREAD

**Issue by BeastAwokenYT** [tommyryan2002/Mangalerts#3]
So the bot shows manga's description but gives embed title manga not found the when u try to track it, it shows manga not found but when u search for manga description it shows manga description and pic but says manga not found

Mangas searched:
I Summoned The Devil To Grant Me A Wish, But I Married Her Instead Since She Was Adorable ~My New Devil Wife~
My Wife Is A Demon Queen

**Comment by tommyryan2002** [comment]
I'm getting success with My Wife is a Demon Queen. But for the first one, that might just be happening because the title in mangadex is absurdly long. Try entering this command exactly `m!track_manga Negai wo Kanaete Moraou to Akuma wo Shoukan Shitakedo, Kawaikattanode Kekkonshimashita ~ Akuma no Niidzuma ~ `
